import os

env = Environment(CC='gcc', CCFLAGS = '-g -Wall -D_DEBUG -O2')

env.Program(target = 'test-x11', source = [Glob('*.c'), Glob('../lib/*/*.c'), Glob('../src/ccore/core/linux/*/*.c'), Glob('../src/ccore/core/common/*/*.c'), Glob('../src/ccore/core/x11/*/*.c')], LIBS=['X11', 'Xrandr', 'Xinerama', 'GL', 'GLU'], LIBPATH=['/usr/lib', '/usr/local/lib', '.'])
