import os

env = Environment(CC='gcc', CCFLAGS = '-g -Wall -O2')

env.Program(target = 'test-x11', source = [Glob('*.c'), Glob('../src/core_x11/*/*.c')], LIBS=['X11', 'Xrandr', 'GL', 'GLU'], LIBPATH=['/usr/lib', '/usr/local/lib', '.'])
