import os

env = Environment(CC='gcc', CCFLAGS = '-g -Wall -D_DEBUG -O2 -I../include/')

env.Program(target = 'featuretest', source = [Glob('*.c'), Glob('../lib/*/*.c'), Glob('../src/ccore/linux/*/*.c'), Glob('../src/ccore/common/*/*.c'), Glob('../src/ccore/x11/*/*.c')], LIBS=['X11', 'Xrandr', 'Xinerama', 'GL', 'GLU'], LIBPATH=['/usr/lib', '/usr/local/lib', '.'])
